/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.RestaurantReviews;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {
    @Test void testRestaurantCreation() {

        Restaurant goodBites = new Restaurant("Good Bites", 4, 2);
        assertEquals("Restaurant{name='Good Bites', stars=4, priceCategory=2}", goodBites.toString());
    }
}
