/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.RestaurantReviews;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {
    @Test void testRestaurantCreation() {

        Restaurant restaurant = new Restaurant("Yum Yum Bowls", 0, 2);

        // Act
        Review review1 = new Review("Great food and service!", "Green G.", 5);
        restaurant.addReview(review1);

        Review review2 = new Review("Average experience.", "M.Jane", 2);
        restaurant.addReview(review2);

        // Assert
        System.out.println("Reviews for " + restaurant.getName() + ":");
        for (Review review : restaurant.getReviews()) {
            System.out.println(review.toString());
        }

        Review review3 = new Review("Not my vibe", "Peter Porker", 1);
        restaurant.addReview(review3);
        System.out.println(review3);
        System.out.println("Updated star rating: " + restaurant.getStars());
    }
}
