/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.RestaurantReviews;

import org.junit.jupiter.api.Test;

class TheaterTest {
    @Test void testRestaurantCreation() {
        // Arrange
        // used ChatGPT to gen review strings, stars and authors
        Theater theater = new Theater("Starlight Playhouse", 0, 2);

        Movie movie1 = new Movie ("Whispering Shadows", "Ava Thompson");
        theater.addMovie(movie1);
        Movie movie2 = new Movie ("Eternal Symphony", "Marcus Rodriguez");
        theater.addMovie(movie2);
        Movie movie3 = new Movie ("Fragments of Time", "Sofia Chen");
        theater.addMovie(movie3);
        // Act
        Review review1 = new Review("The performances at Starlight Playhouse were exceptional, creating an immersive and captivating experience that kept me engaged from start to finish.", "Emily Smith", 4);
        theater.addReview(review1);

        Review review2 = new Review("Starlight Playhouse offers a delightful blend of classic and contemporary productions, showcasing top-notch talent and leaving audiences in awe with its stunning set designs.", "James Thompson", 5);
        theater.addReview(review2);

        // Assert
        System.out.println("Reviews for " + theater.getName() + ":");
        for (Review review : theater.getReviews()) {
            System.out.println(review.toString());
        }

        System.out.println("Movies for " + theater.getName() + ":");
        for (Movie movie : theater.getMovies()) {
            System.out.println(movie.toString());
        }

        Review review3 = new Review("While the acting was commendable, the sound quality at Starlight Playhouse could have been improved, occasionally making it difficult to fully appreciate the performances.", "Samantha Johnson", 3);
        theater.addReview(review3);
        System.out.println(review3);
        System.out.println("Updated star rating: " + theater.getStars());
    }
}
