/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public static int numOfSides = 6;
    private static Random random = new Random();
    public boolean returnRolls() {
        return true;
    }

    public static int[] roll(int n) {
        int[] rolls = new int[n];

        for (int i = 0; i < n; i++) {
            rolls[i] = random.nextInt(numOfSides) + 1;
        }
        return rolls;
    }
}
